-- Generated by nwg-displays on 2026-07-14 at 22:45:34. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-3",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-3"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-3"
})
