-- Generated by nwg-displays on 2026-07-14 at 22:45:36. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@165.0",
    position = "-1920x360",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@180.0",
    position = "0x0",
    scale = 1.0
})
